var lit = [
  {
    'first author name': 'Stacchio24',
    Purpose: 'Performance',
    Year: "'20-'24",
    Device: 'AR/VR HMD',
    Data: 'Mostly GPS',
    'Visual Representation': 'Undefined',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Field',
    '# of Participants': '6-10',
    Title:
      'M-AGEW: Empowering Outdoor Workouts with Data-Driven Augmented Reality Assistance | IEEE Conference Publication | IEEE Xplore',
    'reference number': '48',
  },
  {
    'first author name': 'Liu24',
    Purpose: 'Performance',
    Year: "'20-'24",
    Device: 'HeadPhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'None',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Field',
    '# of Participants': '1-5',
    Title:
      'Vision-based Wearable Steering Assistance for People with Impaired Vision in Jogging',
    'reference number': '49',
  },
  {
    'first author name': 'Simon23',
    Purpose: 'Performance',
    Year: "'20-'24",
    Device: 'MobilePhone',
    Data: 'Mostly Physiological',
    'Visual Representation': 'Only Text',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'No Evaluation',
    '# of Participants': 'Not Applicable',
    Title:
      'Investigating the Use of Augmented Reality to Enhance the Indoor Running Experience on a Treadmill',
    'reference number': '50',
  },
  {
    'first author name': 'Siriaraya23',
    Purpose: 'Performance',
    Year: "'20-'24",
    Device: 'HeadPhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Field',
    '# of Participants': 'Greater than 20',
    Title:
      'Investigating the use of Spatialized Audio Augmented Reality to enhance the outdoor running experience - ScienceDirect',
    'reference number': '51',
  },
  {
    'first author name': 'Hamada22',
    Purpose: 'Performance',
    Year: "'20-'24",
    Device: 'AR/VR HMD',
    Data: 'Mostly Performance',
    'Visual Representation': 'Undefined',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Field',
    '# of Participants': '11-15',
    Title:
      'Solitary Jogging with A Virtual Runner using Smartglasses | IEEE Conference Publication | IEEE Xplore',
    'reference number': '52',
  },
  {
    'first author name': 'Gibson22',
    Purpose: 'Performance',
    Year: "'20-'24",
    Device: 'HeadPhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'None',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Field',
    '# of Participants': '6-10',
    Title:
      'CyberCoach: a Wearable Biofeedback System for Runners | IEEE Conference Publication | IEEE Xplore',
    'reference number': '53',
  },
  {
    'first author name': 'Sporrel21',
    Purpose: 'Performance',
    Year: "'20-'24",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'No Evaluation',
    '# of Participants': 'Not Applicable',
    Title:
      'Frontiers | The Design and Development of a Personalized Leisure Time Physical Activity Application Based on Behavior Change Theories, End-User Perceptions, and Principles From Empirical Data Mining (frontiersin.org)',
    'reference number': '54',
  },
  {
    'first author name': 'Neshati21',
    Purpose: 'Performance',
    Year: "'20-'24",
    Device: 'SmartWatch',
    Data: 'Mostly Physiological',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Lab',
    '# of Participants': 'Greater than 20',
    Title:
      'SF-LG: Space-Filling Line Graphs for Visualizing Interrelated Time-series Data on Smartwatches | Proceedings of the 23rd International Conference on Mobile Human-Computer Interaction (acm.org)',
    'reference number': '55',
  },
  {
    'first author name': 'Niess20',
    Purpose: 'Performance',
    Year: "'20-'24",
    Device: 'SmartWatch',
    Data: 'Mostly Performance',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Lab',
    '# of Participants': '16-20',
    Title:
      'Exploring Fitness Tracker Visualisations to Avoid Rumination | 22nd International Conference on Human-Computer Interaction with Mobile Devices and Services (acm.org)',
    'reference number': '56',
  },
  {
    'first author name': 'Neshati19',
    Purpose: 'Performance',
    Year: "'15-'19",
    Device: 'SmartWatch',
    Data: 'Mostly Physiological',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Lab',
    '# of Participants': 'Greater than 20',
    Title:
      'G-Sparks: Glanceable Sparklines on Smartwatches • Graphics Interface',
    'reference number': '57',
  },
  {
    'first author name': 'Smyth18',
    Purpose: 'Performance',
    Year: "'15-'19",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'No Evaluation',
    '# of Participants': 'Not Applicable',
    Title:
      'An Analysis of Case Representations for Marathon Race Prediction and Planning | SpringerLink',
    'reference number': '58',
  },
  {
    'first author name': 'Colley18',
    Purpose: 'Performance',
    Year: "'15-'19",
    Device: 'Other Body-worn Device',
    Data: 'Mostly Performance',
    'Visual Representation': 'Undefined',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Lab',
    '# of Participants': '6-10',
    Title:
      'Shoe integrated displays | Proceedings of the 10th Nordic Conference on Human-Computer Interaction (acm.org)',
    'reference number': '59',
  },
  {
    'first author name': 'Vos17',
    Purpose: 'Performance',
    Year: "'15-'19",
    Device: 'MobilePhone',
    Data: 'Mostly Physiological',
    'Visual Representation': 'Icon + Text',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Field',
    '# of Participants': 'Greater than 20',
    Title:
      'From Problem to Solution: Developing a Personalized Smartphone Application for Recreational Runners following a Three-step Design Approach',
    'reference number': '60',
  },
  {
    'first author name': 'Herrmanny16',
    Purpose: 'Performance',
    Year: "'15-'19",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Field',
    '# of Participants': 'Greater than 20',
    Title:
      'Supporting Users in Setting Effective Goals in Activity Tracking | SpringerLink',
    'reference number': '61',
  },
  {
    'first author name': 'Busa16',
    Purpose: 'Performance',
    Year: "'15-'19",
    Device: 'ExternalDisplay',
    Data: 'Mostly Physiological',
    'Visual Representation': 'Only Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Lab',
    '# of Participants': '11-15',
    Title:
      'Head and Tibial Acceleration as a Function of Stride Frequency and Visual Feedback during Running | PLOS ONE',
    'reference number': '62',
  },
  {
    'first author name': 'Gouveia16',
    Purpose: 'Performance',
    Year: "'15-'19",
    Device: 'SmartWatch',
    Data: 'Mostly Performance',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Field',
    '# of Participants': '11-15',
    Title:
      'Exploring the design space of glanceable feedback for physical activity trackers | Proceedings of the 2016 ACM International Joint Conference on Pervasive and Ubiquitous Computing',
    'reference number': '63',
  },
  {
    'first author name': 'Chen15',
    Purpose: 'Performance',
    Year: "'15-'19",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'None',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Lab',
    '# of Participants': '6-10',
    Title:
      'A wearable virtual coach for Marathon beginners | IEEE Conference Publication | IEEE Xplore',
    'reference number': '64',
  },
  {
    'first author name': 'Hao15',
    Purpose: 'Performance',
    Year: "'15-'19",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Field',
    '# of Participants': '11-15',
    Title:
      'RunBuddy | Proceedings of the 2015 ACM International Joint Conference on Pervasive and Ubiquitous Computing',
    'reference number': '65',
  },
  {
    'first author name': 'Richer15',
    Purpose: 'Performance',
    Year: "'15-'19",
    Device: 'SmartWatch',
    Data: 'Mostly Physiological',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Field',
    '# of Participants': '6-10',
    Title:
      'Novel human computer interaction principles for cardiac feedback using google glass and Android wear | IEEE Conference Publication | IEEE Xplore (uq.edu.au)',
    'reference number': '66',
  },
  {
    'first author name': 'Kitahara14',
    Purpose: 'Performance',
    Year: "'10-'14",
    Device: 'HeadPhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'None',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Field',
    '# of Participants': '6-10',
    Title:
      'Music Synchronizer with Runner’s Pace for Supporting Steady Pace Jogging | SpringerLink',
    'reference number': '67',
  },
  {
    'first author name': 'Fortmann12',
    Purpose: 'Performance',
    Year: "'10-'14",
    Device: 'HeadPhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Only Text',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Field',
    '# of Participants': '1-5',
    Title:
      'PaceGuard | Proceedings of the 14th international conference on Human-computer interaction with mobile devices and services companion (acm.org)',
    'reference number': '68',
  },
  {
    'first author name': 'Rubisch10',
    Purpose: 'Performance',
    Year: "'10-'14",
    Device: 'MobilePhone',
    Data: 'Mostly Physiological',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'No Evaluation',
    '# of Participants': 'Not Applicable',
    Title:
      'A mobile music concept as support for achieving target heart rate in preventive and recreational endurance training | Proceedings of the 5th Audio Mostly Conference: A Conference on Interaction with Sound (acm.org)',
    'reference number': '69',
  },
  {
    'first author name': 'Oliver06',
    Purpose: 'Performance',
    Year: "'05-'09",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Lab',
    '# of Participants': '1-5',
    Title:
      'MPTrain | Proceedings of the 8th conference on Human-computer interaction with mobile devices and services (acm.org)',
    'reference number': '70',
  },
  {
    'first author name': 'Gockley06',
    Purpose: 'Performance',
    Year: "'05-'09",
    Device: 'SmartWatch',
    Data: 'Mostly Performance',
    'Visual Representation': 'Icon + Text',
    'Additional Modality': 'None',
    'Has Evaluation': 'No Evaluation',
    '# of Participants': 'Not Applicable',
    Title:
      "AVIVA | CHI '06 Extended Abstracts on Human Factors in Computing Systems (acm.org)",
    'reference number': '71',
  },
  {
    'first author name': 'Makikawa04',
    Purpose: 'Performance',
    Year: "'00-'04",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Only Text',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Field',
    '# of Participants': '1-5',
    Title:
      'Jogging support system with portable monitoring device and health manage software - PubMed (nih.gov)',
    'reference number': '72',
  },
    {
    'first author name': 'Eom23',
    Purpose: 'Technique',
    Year: "'20-'24",
    Device: 'MobilePhone',
    Data: 'Mostly Technique',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Field',
    '# of Participants': '1-5',
    Title:
      'Running Gait Posture Optimization Using Embedded IoT Sensor Shoes | IEEE Conference Publication | IEEE Xplore',
    'reference number': '5',
  },
  {
    'first author name': 'Schiewe20',
    Purpose: 'Technique',
    Year: "'20-'24",
    Device: 'SmartWatch',
    Data: 'Mostly Technique',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Lab',
    '# of Participants': 'Greater than 20',
    Title:
      'A Study on Real-Time Visualizations During Sports Activities on Smartwatches (acm.org)',
    'reference number': '6',
  },
  {
    'first author name': 'Morris20',
    Purpose: 'Technique',
    Year: "'20-'24",
    Device: 'MobilePhone',
    Data: 'Mostly Technique',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Field',
    '# of Participants': 'Greater than 20',
    Title:
      'Using real‐time biofeedback to alter running biomechanics: A randomized controlled trial - Morris - 2020 - TRANSLATIONAL SPORTS MEDICINE - Wiley Online Library',
    'reference number': '7',
  },
    {
    'first author name': 'Valsted17',
    Purpose: 'Technique',
    Year: "'15-'19",
    Device: 'Other Body-worn Device',
    Data: 'Mostly Technique',
    'Visual Representation': 'None',
    'Additional Modality': 'Haptic',
    'Has Evaluation': 'In Field',
    '# of Participants': '16-20',
    Title: 'Strive: exploring assistive haptic feedback on the run',
    'reference number': '8',
  },
  {
    'first author name': 'Hassan17',
    Purpose: 'Technique',
    Year: "'15-'19",
    Device: 'Other Body-worn Device',
    Data: 'Mostly Technique',
    'Visual Representation': 'None',
    'Additional Modality': 'Haptic',
    'Has Evaluation': 'In Lab',
    '# of Participants': '16-20',
    Title:
      'FootStriker: An EMS-based Foot Strike Assistant for Running: Proceedings of the ACM on Interactive, Mobile, Wearable and Ubiquitous Technologies: Vol 1, No 1',
    'reference number': '9',
  },
  {
    'first author name': 'Seuter16',
    Purpose: 'Technique',
    Year: "'15-'19",
    Device: 'AR/VR HMD',
    Data: 'Mostly Technique',
    'Visual Representation': 'Undefined',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Field',
    '# of Participants': '6-10',
    Title:
      'Live-feedback from the IMUs | Proceedings of the 2016 ACM International Joint Conference on Pervasive and Ubiquitous Computing: Adjunct',
    'reference number': '10',
  },
  {
    'first author name': 'Nylander14',
    Purpose: 'Technique',
    Year: "'10-'14",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Only Chart/Graph',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Lab',
    '# of Participants': '6-10',
    Title: 'RunRight - Real-time visual and audio feedback on running',
    'reference number': '11',
  },
  {
    'first author name': 'Tominaga14',
    Purpose: 'Technique',
    Year: "'10-'14",
    Device: 'Drone/Robot',
    Data: 'Mostly Multimedia',
    'Visual Representation': 'Undefined',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Field',
    '# of Participants': '6-10',
    Title:
      'Around me: A system with an escort robot providing a sports player’s self-images.',
    'reference number': '12',
  },
  {
    'first author name': 'Anas14',
    Purpose: 'Technique',
    Year: "'10-'14",
    Device: 'ExternalDisplay',
    Data: 'Mostly Technique',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Lab',
    '# of Participants': '1-5',
    Title:
      'An Instrumented Insole System for Gait Monitoring and Analysis | International Journal of Online and Biomedical Engineering',
    'reference number': '13',
  },
  {
    'first author name': 'Strohrmann13',
    Purpose: 'Technique',
    Year: "'10-'14",
    Device: 'MobilePhone',
    Data: 'Mostly Technique',
    'Visual Representation': 'None',
    'Additional Modality': 'Haptic',
    'Has Evaluation': 'In Field',
    '# of Participants': 'Greater than 20',
    Title: 'Can Smartphones Help with Running Technique? - ScienceDirect',
    'reference number': '14',
  },
  {
    'first author name': 'Eriksson11',
    Purpose: 'Technique',
    Year: "'10-'14",
    Device: 'ExternalDisplay',
    Data: 'Mostly Technique',
    'Visual Representation': 'Only Chart/Graph',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Lab',
    '# of Participants': '16-20',
    Title:
      'Full article: Immediate effect of visual and auditory feedback to control the running mechanics of well-trained athletes (tandfonline.com)',
    'reference number': '15',
  },
  {
    'first author name': 'Higuchi11',
    Purpose: 'Technique',
    Year: "'10-'14",
    Device: 'AR/VR HMD',
    Data: 'Mostly Technique',
    'Visual Representation': 'Undefined',
    'Additional Modality': 'None',
    'Has Evaluation': 'No Evaluation',
    '# of Participants': 'Not Applicable',
    Title:
      'Flying sports assistant | Proceedings of the 2nd Augmented Human International Conference (acm.org)',
    'reference number': '16',
  },
  {
    'first author name': 'Buttussi08',
    Purpose: 'Technique',
    Year: "'05-'09",
    Device: 'MobilePhone',
    Data: 'Mostly Physiological',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'No Evaluation',
    '# of Participants': 'Not Applicable',
    Title:
      'MOPET: A context-aware and user-adaptive wearable system for fitness training - ScienceDirect',
    'reference number': '17',
  },
  {
    'first author name': 'Balasubramaniam23',
    Purpose: 'Experiential',
    Year: "'20-'24",
    Device: 'Drone/Robot',
    Data: 'Mostly Multimedia',
    'Visual Representation': 'Undefined',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Field',
    '# of Participants': '6-10',
    Title:
      'Running with a Drone for Pace Setting, Video Reflection, and Beyond: An Experiential Study',
    'reference number': '28',
  },
  {
    'first author name': 'Van Renswouw21',
    Purpose: 'Experiential',
    Year: "'20-'24",
    Device: 'HeadPhone',
    Data: 'Mostly Technique',
    'Visual Representation': 'None',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Field',
    '# of Participants': '1-5',
    Title:
      'Sensation: Sonifying the Urban Running Experience | Extended Abstracts of the 2021 CHI Conference on Human Factors in Computing Systems (acm.org)',
    'reference number': '29',
  },
  {
    'first author name': 'Noordin20',
    Purpose: 'Experiential',
    Year: "'20-'24",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'No Evaluation',
    '# of Participants': 'Not Applicable',
    Title:
      'Stay fit during COVID-19, a study using interactive jogging application (JOGA)',
    'reference number': '30',
  },
  {
    'first author name': 'Álvarez20',
    Purpose: 'Experiential',
    Year: "'20-'24",
    Device: 'MobilePhone',
    Data: 'Mostly Physiological',
    'Visual Representation': 'None',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'No Evaluation',
    '# of Participants': 'Not Applicable',
    Title:
      'Mobile music recommendations for runners based on location and emotions: The DJ-Running system - ScienceDirect',
    'reference number': '31',
  },
  {
    'first author name': 'Gallo20',
    Purpose: 'Experiential',
    Year: "'20-'24",
    Device: 'MobilePhone',
    Data: 'Mostly GPS',
    'Visual Representation': 'None',
    'Additional Modality': 'Sonification, Haptic',
    'Has Evaluation': 'In Field',
    '# of Participants': 'Greater than 20',
    Title:
      'RunAhead: Exploring Head Scanning based Navigation for Runners | Proceedings of the 2020 CHI Conference on Human Factors in Computing Systems (acm.org)',
    'reference number': '32',
  },
  {
    'first author name': 'Ioannou19',
    Purpose: 'Experiential',
    Year: "'15-'19",
    Device: 'AR/VR HMD',
    Data: 'Mostly Physiological',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Lab',
    '# of Participants': 'Greater than 20',
    Title:
      'Virtual Performance Augmentation in an Immersive Jump & Run Exergame | Proceedings of the 2019 CHI Conference on Human Factors in Computing Systems (acm.org)',
    'reference number': '33',
  },
  {
    'first author name': 'Witkowski18',
    Purpose: 'Experiential',
    Year: "'15-'19",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Only Text',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'No Evaluation',
    '# of Participants': 'Not Applicable',
    Title:
      'Running With Zombies: Capturing New Worlds Through Movement and Visibility Practices With Zombies, Run! - Emma Witkowski, 2018 (sagepub.com)',
    'reference number': '34',
  },
  {
    'first author name': 'Ali18',
    Purpose: 'Experiential',
    Year: "'15-'19",
    Device: 'AR/VR HMD',
    Data: 'Mostly Performance',
    'Visual Representation': 'Only Text',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Lab',
    '# of Participants': 'Greater than 20',
    Title:
      'Virtual reality as a physical training assistant | IEEE Conference Publication | IEEE Xplore',
    'reference number': '35',
  },
  {
    'first author name': 'Hannan16',
    Purpose: 'Experiential',
    Year: "'15-'19",
    Device: 'MobilePhone',
    Data: 'Mostly Physiological',
    'Visual Representation': 'Only Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'No Evaluation',
    '# of Participants': 'Not Applicable',
    Title:
      'JogChalking | Proceedings of the 2016 ACM Conference Companion Publication on Designing Interactive Systems',
    'reference number': '36',
  },
  {
    'first author name': 'Mueller15',
    Purpose: 'Experiential',
    Year: "'15-'19",
    Device: 'Drone/Robot',
    Data: 'Mostly Performance',
    'Visual Representation': 'Undefined',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Field',
    '# of Participants': '11-15',
    Title:
      'Jogging with a Quadcopter | Proceedings of the 33rd Annual ACM Conference on Human Factors in Computing Systems',
    'reference number': '37',
  },
  {
    'first author name': 'McKenzie14',
    Purpose: 'Experiential',
    Year: "'10-'14",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Field',
    '# of Participants': '11-15',
    Title:
      'Design Elements and Feasibility of an Organized Multiplayer Mobile Active Videogame for Primary School-Aged Children | Games for Health Journal (liebertpub.com)',
    'reference number': '38',
  },
  {
    'first author name': 'McGookin13',
    Purpose: 'Experiential',
    Year: "'10-'14",
    Device: 'SmartWatch',
    Data: 'Mostly GPS',
    'Visual Representation': 'Only Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'No Evaluation',
    '# of Participants': 'Not Applicable',
    Title:
      "Investigating and supporting undirected navigation for runners | CHI '13 Extended Abstracts on Human Factors in Computing Systems (acm.org)",
    'reference number': '39',
  },
  {
    'first author name': 'Morie11',
    Purpose: 'Experiential',
    Year: "'10-'14",
    Device: 'ExternalDisplay',
    Data: 'Mostly Physiological',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Lab',
    '# of Participants': 'Greater than 20',
    Title:
      'Report on a Preliminary Study Using Breath Control and a Virtual Jogging Scenario as Biofeedback for Resilience Training | SpringerLink',
    'reference number': '40',
  },
  {
    'first author name': 'Turunen11',
    Purpose: 'Experiential',
    Year: "'10-'14",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Only Text',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Lab',
    '# of Participants': '6-10',
    Title:
      'Multimodal and mobile conversational Health and Fitness Companions | Computer Speech and Language (acm.org)',
    'reference number': '41',
  },
  {
    'first author name': 'Buttussi10',
    Purpose: 'Experiential',
    Year: "'10-'14",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Only Text',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Field',
    '# of Participants': '11-15',
    Title:
      'Smarter Phones for Healthier Lifestyles: An Adaptive Fitness Game | IEEE Journals & Magazine | IEEE Xplore (uq.edu.au)',
    'reference number': '42',
  },
  {
    'first author name': 'Kwon09',
    Purpose: 'Experiential',
    Year: "'05-'09",
    Device: 'ExternalDisplay',
    Data: 'Mostly Technique',
    'Visual Representation': 'Only Text',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Lab',
    '# of Participants': '6-10',
    Title:
      "ReadingMate | CHI '09 Extended Abstracts on Human Factors in Computing Systems (acm.org)",
    'reference number': '43',
  },
  {
    'first author name': 'Yamamoto08',
    Purpose: 'Experiential',
    Year: "'05-'09",
    Device: 'HeadPhone',
    Data: 'Mostly Multimedia',
    'Visual Representation': 'None',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Lab',
    '# of Participants': '1-5',
    Title:
      'Foot-Step Input Method for Operating Information Devices While Jogging | Proceedings of the 2008 International Symposium on Applications and the Internet (acm.org)',
    'reference number': '44',
  },
  {
    'first author name': 'Sakata06',
    Purpose: 'Experiential',
    Year: "'05-'09",
    Device: 'HeadPhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'None',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'No Evaluation',
    '# of Participants': 'Not Applicable',
    Title: 'Situated Music: An Application to Interactive Jogging',
    'reference number': '45',
  },
  {
    'first author name': 'Asselin05',
    Purpose: 'Experiential',
    Year: "'05-'09",
    Device: 'HeadPhone',
    Data: 'Mostly Physiological',
    'Visual Representation': 'None',
    'Additional Modality': 'Sonification, Haptic',
    'Has Evaluation': 'In Lab',
    '# of Participants': 'Greater than 20',
    Title:
      'Implementation and evaluation of the personal wellness coach | IEEE Conference Publication | IEEE Xplore',
    'reference number': '46',
  },
  {
    'first author name': 'Tong24',
    Purpose: 'Social',
    Year: "'20-'24",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Field',
    '# of Participants': '11-15',
    Title:
      'VisTellAR: Embedding Data Visualization to Short-form Videos Using Mobile Augmented Reality.',
    'reference number': '20',
  },
  {
    'first author name': 'Baldursson21',
    Purpose: 'Social',
    Year: "'20-'24",
    Device: 'Drone/Robot',
    Data: 'Mostly Performance',
    'Visual Representation': 'Undefined',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Lab',
    '# of Participants': '6-10',
    Title:
      'DroRun: Drone Visual Interactions to Mediate a Running Group | Companion of the 2021 ACM/IEEE International Conference on Human-Robot Interaction',
    'reference number': '21',
  },
  {
    'first author name': 'Woźniak15',
    Purpose: 'Social',
    Year: "'15-'19",
    Device: 'Other Body-worn Device',
    Data: 'Mostly Performance',
    'Visual Representation': 'None',
    'Additional Modality': 'Haptic',
    'Has Evaluation': 'In Field',
    '# of Participants': '16-20',
    Title:
      'RUFUS | Proceedings of the 17th International Conference on Human-Computer Interaction with Mobile Devices and Services (acm.org)',
    'reference number': '22',
  },
  {
    'first author name': 'Kishino14',
    Purpose: 'Social',
    Year: "'10-'14",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Only Text',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Field',
    '# of Participants': '16-20',
    Title:
      'Virtual Marathon System Where Humans and Agents Compete | Proceedings of the 4th International Conference on Web Intelligence, Mining and Semantics (WIMS14) (acm.org)',
    'reference number': '23',
  },
  {
    'first author name': 'Mauriello14',
    Purpose: 'Social',
    Year: "'10-'14",
    Device: 'Other Body-worn Device',
    Data: 'Mostly Performance',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Field',
    '# of Participants': 'Greater than 20',
    Title:
      'Social fabric fitness | Proceedings of the SIGCHI Conference on Human Factors in Computing Systems (acm.org)',
    'reference number': '24',
  },
  {
    'first author name': 'Häkkilä13',
    Purpose: 'Social',
    Year: "'10-'14",
    Device: 'ExternalDisplay',
    Data: 'Mostly Performance',
    'Visual Representation': 'Only Text',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Lab',
    '# of Participants': 'Greater than 20',
    Title:
      'Jogging in a virtual city | Proceedings of the 12th International Conference on Mobile and Ubiquitous Multimedia (acm.org)',
    'reference number': '25',
  },
  {
    'first author name': 'Mueller07',
    Purpose: 'Social',
    Year: "'05-'09",
    Device: 'HeadPhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'None',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Lab',
    '# of Participants': '1-5',
    Title:
      'Jogging over a distance: Supporting a "jogging together" experience although being apart',
    'reference number': '26',
  },
  {
    'first author name': 'Consolvo06',
    Purpose: 'Social',
    Year: "'05-'09",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Only Text',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Field',
    '# of Participants': '11-15',
    Title:
      'Design requirements for technologies that encourage physical activity | Proceedings of the SIGCHI Conference on Human Factors in Computing Systems (acm.org)',
    'reference number': '27',
  },
  {
    'first author name': 'Curmi14',
    Purpose: 'Performance, Social',
    Year: "'10-'14",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'Haptic',
    'Has Evaluation': 'No Evaluation',
    '# of Participants': 'Not Applicable',
    Title:
      'Sharing real-time biometric data across social networks | Proceedings of the 2014 conference on Designing interactive systems (acm.org)',
    'reference number': '1',
  },
  {
    'first author name': 'Mulas11',
    Purpose: 'Performance, Social',
    Year: "'10-'14",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Icon + Text',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Lab',
    '# of Participants': '1-5',
    Title:
      'Everywhere run | Proceedings of the 8th International Conference on Advances in Computer Entertainment Technology (acm.org)',
    'reference number': '2',
  },
  {
    'first author name': 'Oliveira08',
    Purpose: 'Performance, Social',
    Year: "'05-'09",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Icon + Text',
    'Additional Modality': 'Sonification',
    'Has Evaluation': 'In Field',
    '# of Participants': '6-10',
    Title:
      'TripleBeat | Proceedings of the 10th international conference on Human computer interaction with mobile devices and services (acm.org)',
    'reference number': '3',
  },
  {
    'first author name': 'Ahtinen08',
    Purpose: 'Performance, Social',
    Year: "'05-'09",
    Device: 'MobilePhone',
    Data: 'Mostly Performance',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Field',
    '# of Participants': 'Greater than 20',
    Title:
      'Tracking Outdoor Sports --- User Experience Perspective | Proceedings of the European Conference on Ambient Intelligence (acm.org)',
    'reference number': '4',
  },
  {
    'first author name': 'Burr22',
    Purpose: 'Technique, Experiential',
    Year: "'20-'24",
    Device: 'ExternalDisplay',
    Data: 'Mostly Technique',
    'Visual Representation': 'Only Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Lab',
    '# of Participants': '11-15',
    Title:
      'Breathing Training on the Run: Exploring Users Perception on a Gamified Breathing Training Application During Treadmill Running | SpringerLink',
    'reference number': '18',
  },
  {
    'first author name': 'Kiss17',
    Purpose: 'Technique, Performance',
    Year: "'15-'19",
    Device: 'MobilePhone',
    Data: 'Mostly Technique',
    'Visual Representation': 'Text + Chart/Graph',
    'Additional Modality': 'None',
    'Has Evaluation': 'In Lab',
    '# of Participants': '1-5',
    Title:
      'RunMerge: Towards Enhanced Proprioception for Advanced Amateur Runners (acm.org)',
    'reference number': '19',
  },
  {
    'first author name': 'Ahn09',
    Purpose: 'Experiential, Social',
    Year: "'05-'09",
    Device: 'ExternalDisplay',
    Data: 'Mostly Performance',
    'Visual Representation': 'Only Text',
    'Additional Modality': 'Haptic',
    'Has Evaluation': 'In Lab',
    '# of Participants': '16-20',
    Title:
      'Running or gaming | Proceedings of the International Conference on Advances in Computer Entertainment Technology (acm.org)',
    'reference number': '47',
  },
];

var node_list = [
  {
    0: 'Performance',
    1: 'Technique',
    2: 'Experiential',
    3: 'Social',
    4: 'Technique, Experiential',
    5: 'Technique, Performance',
    6: 'Performance, Social',
    7: 'Experiential, Social',
    title: 'Purpose',
  },
  {
    0: "'20-'24",
    1: "'15-'19",
    2: "'10-'14",
    3: "'05-'09",
    4: "'00-'04",
    5: '',
    6: '',
    7: '',
    title: 'Year',
  },
  {
    0: 'MobilePhone',
    1: 'SmartWatch',
    2: 'HeadPhone',
    3: 'ExternalDisplay',
    4: 'AR/VR HMD',
    5: 'Other Body-worn Device',
    6: 'Drone/Robot',
    7: '',
    title: 'Device',
  },
  {
    0: 'Mostly Performance',
    1: 'Mostly Physiological',
    2: 'Mostly Technique',
    3: 'Mostly Multimedia',
    4: 'Mostly GPS',
    5: '',
    6: '',
    7: '',
    title: 'Data',
  },
  {
    0: 'Only Text',
    1: 'Only Chart/Graph',
    2: 'Text + Chart/Graph',
    3: 'Undefined',
    4: 'Icon + Text',
    5: 'None',
    6: '',
    7: '',
    title: 'Visual Representation',
  },
  {
    0: 'Sonification',
    1: 'Haptic',
    2: 'Sonification, Haptic',
    3: 'None',
    4: '',
    5: '',
    6: '',
    7: '',
    title: 'Additional Modality',
  },
  {
    0: 'In Field',
    1: 'In Lab',
    2: 'No Evaluation',
    3: '',
    4: '',
    5: '',
    6: '',
    7: '',
    title: 'Has Evaluation',
  },
  {
    0: '1-5',
    1: '6-10',
    2: '11-15',
    3: '16-20',
    4: 'Greater than 20',
    5: 'Not Applicable',
    6: '',
    7: '',
    title: '# of Participants',
  },
];
