var lit = [{'first author name': "Stacchio24", 'Purpose': "Instructional", 'Year': "'20-'24", 'Device': "AR/VR HMD", 'Data': "Performance, Location-based", 'Data Abstraction': "Abstract, Mixed", 'Visual Encoding': "2D, Non-visual", 'Embeddedness': "Co-located", 'Interaction Space': "Focal-Extrapersonal", 'Evaluation': "In Field", 'Title': "M-AGEW: Empowering Outdoor Workouts with Data-Driven Augmented Reality Assistance | IEEE Conference Publication | IEEE Xplore", 'Unnamed: 11': "Stacchio24", 'reference number': '17','image': 'images/Stacchio24.png'},
    {'first author name': "Simon23", 'Purpose': "Instructional", 'Year': "'20-'24", 'Device': "MobilePhone", 'Data': "Performance, Physiological", 'Data Abstraction': "Abstract", 'Visual Encoding': "Textual, Non-visual", 'Embeddedness': "Co-located", 'Interaction Space': "Focal-Extrapersonal", 'Evaluation': "No Evaluation", 'Title': "Investigating the Use of Augmented Reality to Enhance the Indoor Running Experience on a Treadmill", 'Unnamed: 11': "Simon23", 'reference number': '18','image': 'images/Simon23.png'},
    {'first author name': "Siriaraya23", 'Purpose': "Instructional", 'Year': "'20-'24", 'Device': "HeadPhone", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D, Non-visual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "Investigating the use of Spatialized Audio Augmented Reality to enhance the outdoor running experience - ScienceDirect", 'Unnamed: 11': "Siriaraya23", 'reference number': '19','image': 'images/Siriaraya23.png'},
    {'first author name': "Eom23", 'Purpose': "Instructional", 'Year': "'20-'24", 'Device': "MobilePhone", 'Data': "Performance, Technique, Location-based", 'Data Abstraction': "Abstract, Mixed", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "Running Gait Posture Optimization Using Embedded IoT Sensor Shoes | IEEE Conference Publication | IEEE Xplore", 'Unnamed: 11': "Eom23", 'reference number': '20','image': 'images/Eom23.png'},
    //{'first author name': "Gibson22", 'Purpose': "Instructional", 'Year': "'20-'24", 'Device': "HeadPhone", 'Data': "Performance, Technique", 'Data Abstraction': "Abstract", 'Visual Encoding': "Non-visual", 'Embeddedness': "N.A.", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "CyberCoach: a Wearable Biofeedback System for Runners | IEEE Conference Publication | IEEE Xplore", 'Unnamed: 11': "Gibson22", 'reference number': '21','image': 'images/Gibson22.png'},
    {'first author name': "Sporrel21", 'Purpose': "Instructional", 'Year': "'20-'24", 'Device': "MobilePhone", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D, Non-visual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "No Evaluation", 'Title': "Frontiers | The Design and Development of a Personalized Leisure Time Physical Activity Application Based on Behavior Change Theories, End-User Perceptions, and Principles From Empirical Data Mining (frontiersin.org)", 'Unnamed: 11': "Sporrel21", 'reference number': '22','image': 'images/Sporrel21.png'},
    {'first author name': "Neshati21", 'Purpose': "Instructional", 'Year': "'20-'24", 'Device': "SmartWatch", 'Data': "Performance, Physiological", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Lab", 'Title': "SF-LG: Space-Filling Line Graphs for Visualizing Interrelated Time-series Data on Smartwatches | Proceedings of the 23rd International Conference on Mobile Human-Computer Interaction (acm.org)", 'Unnamed: 11': "Neshati21", 'reference number': '23','image': 'images/Neshati21.png'},
    {'first author name': "Schiewe20", 'Purpose': "Instructional", 'Year': "'20-'24", 'Device': "SmartWatch", 'Data': "Technique", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Lab", 'Title': "A Study on Real-Time Visualizations During Sports Activities on Smartwatches (acm.org)", 'Unnamed: 11': "Schiewe20", 'reference number': '24','image': 'images/Schiewe20.png'},
    {'first author name': "Morris20", 'Purpose': "Instructional", 'Year': "'20-'24", 'Device': "MobilePhone", 'Data': "Performance, Technique", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D, Non-visual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "Using real‐time biofeedback to alter running biomechanics: A randomized controlled trial - Morris - 2020 - TRANSLATIONAL SPORTS MEDICINE - Wiley Online Library", 'Unnamed: 11': "Morris20", 'reference number': '25','image': 'images/Morris20.png'},
    {'first author name': "Neshati19", 'Purpose': "Instructional", 'Year': "'15-'19", 'Device': "SmartWatch", 'Data': "Performance, Physiological, Location-based", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Lab", 'Title': "G-Sparks: Glanceable Sparklines on Smartwatches • Graphics Interface", 'Unnamed: 11': "Neshati19", 'reference number': '26','image': 'images/Neshati19.png'},
    {'first author name': "Smyth18", 'Purpose': "Instructional", 'Year': "'15-'19", 'Device': "MobilePhone", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "No Evaluation", 'Title': "An Analysis of Case Representations for Marathon Race Prediction and Planning | SpringerLink", 'Unnamed: 11': "Smyth18", 'reference number': '27','image': 'images/Smyth18.png'},
    {'first author name': "Colley18", 'Purpose': "Instructional", 'Year': "'15-'19", 'Device': "Other Body-worn Device", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D", 'Embeddedness': "Embedded", 'Interaction Space': "Peripersonal", 'Evaluation': "In Lab", 'Title': "Shoe integrated displays | Proceedings of the 10th Nordic Conference on Human-Computer Interaction (acm.org)", 'Unnamed: 11': "Colley18", 'reference number': '28','image': 'images/Colley18.png'},
    {'first author name': "Kiss17", 'Purpose': "Instructional", 'Year': "'15-'19", 'Device': "MobilePhone", 'Data': "Performance, Technique", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Lab", 'Title': "RunMerge: Towards Enhanced Proprioception for Advanced Amateur Runners (acm.org)", 'Unnamed: 11': "Kiss17", 'reference number': '29','image': 'images/Kiss17.png'},
    //{'first author name': "Valsted17", 'Purpose': "Instructional", 'Year': "'15-'19", 'Device': "Other Body-worn Device", 'Data': "Physiological", 'Data Abstraction': "Abstract", 'Visual Encoding': "Non-visual", 'Embeddedness': "N.A.", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "Strive: exploring assistive haptic feedback on the run", 'Unnamed: 11': "Valsted17", 'reference number': '30','image': 'images/Valsted17.png'},
    {'first author name': "Vos17", 'Purpose': "Instructional", 'Year': "'15-'19", 'Device': "MobilePhone", 'Data': "Performance, Physiological, Location-based", 'Data Abstraction': "Abstract, Mixed", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "From Problem to Solution: Developing a Personalized Smartphone Application for Recreational Runners following a Three-step Design Approach", 'Unnamed: 11': "Vos17", 'reference number': '31','image': 'images/Vos17.png'},
    //{'first author name': "Hassan17", 'Purpose': "Instructional", 'Year': "'15-'19", 'Device': "Other Body-worn Device", 'Data': "Technique", 'Data Abstraction': "Abstract", 'Visual Encoding': "Non-visual", 'Embeddedness': "N.A.", 'Interaction Space': "Peripersonal", 'Evaluation': "In Lab", 'Title': "FootStriker: An EMS-based Foot Strike Assistant for Running: Proceedings of the ACM on Interactive, Mobile, Wearable and Ubiquitous Technologies: Vol 1, No 1", 'Unnamed: 11': "Hassan17", 'reference number': '32','image': 'images/Hassan17.png'},
    {'first author name': "Seuter16", 'Purpose': "Instructional", 'Year': "'15-'19", 'Device': "AR/VR HMD", 'Data': "Technique", 'Data Abstraction': "Spatial", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "Live-feedback from the IMUs | Proceedings of the 2016 ACM International Joint Conference on Pervasive and Ubiquitous Computing: Adjunct", 'Unnamed: 11': "Seuter16", 'reference number': '33','image': 'images/Seuter16.png'},
    {'first author name': "Gouveia16", 'Purpose': "Instructional", 'Year': "'15-'19", 'Device': "SmartWatch", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "Exploring the design space of glanceable feedback for physical activity trackers | Proceedings of the 2016 ACM International Joint Conference on Pervasive and Ubiquitous Computing", 'Unnamed: 11': "Gouveia16", 'reference number': '34','image': 'images/Gouveia16.png'},
    {'first author name': "Hao15", 'Purpose': "Instructional", 'Year': "'15-'19", 'Device': "MobilePhone", 'Data': "Performance, Physiological", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D, Non-visual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "RunBuddy | Proceedings of the 2015 ACM International Joint Conference on Pervasive and Ubiquitous Computing", 'Unnamed: 11': "Hao15", 'reference number': '35','image': 'images/Hao15.png'},
    {'first author name': "Richer15", 'Purpose': "Instructional", 'Year': "'15-'19", 'Device': "SmartWatch", 'Data': "Performance, Physiological", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "Novel human computer interaction principles for cardiac feedback using google glass and Android wear | IEEE Conference Publication | IEEE Xplore", 'Unnamed: 11': "Richer15", 'reference number': '36','image': 'images/Richer15.png'},
    {'first author name': "Curmi14", 'Purpose': "Instructional", 'Year': "'10-'14", 'Device': "MobilePhone", 'Data': "Performance, Physiological, Location-based", 'Data Abstraction': "Abstract, Mixed", 'Visual Encoding': "Textual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "No Evaluation", 'Title': "Sharing real-time biometric data across social networks | Proceedings of the 2014 conference on Designing interactive systems (acm.org)", 'Unnamed: 11': "Curmi14", 'reference number': '49','image': 'images/Curmi14.png'},
    {'first author name': "Nylander14", 'Purpose': "Instructional", 'Year': "'10-'14", 'Device': "MobilePhone", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D, Non-visual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Lab", 'Title': "RunRight - Real-time visual and audio feedback on running", 'Unnamed: 11': "Nylander14", 'reference number': '37','image': 'images/Nylander14.png'},
    //{'first author name': "Kitahara14", 'Purpose': "Instructional", 'Year': "'10-'14", 'Device': "HeadPhone", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "Non-visual", 'Embeddedness': "N.A.", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "Music Synchronizer with Runner’s Pace for Supporting Steady Pace Jogging | SpringerLink", 'Unnamed: 11': "Kitahara14", 'reference number': '38','image': 'images/Kitahara14.png'},
    {'first author name': "Tominaga14", 'Purpose': "Instructional", 'Year': "'10-'14", 'Device': "ExternalDisplay", 'Data': "Technique, Multimedia", 'Data Abstraction': "Spatial", 'Visual Encoding': "2D", 'Embeddedness': "Embedded", 'Interaction Space': "Focal-Extrapersonal", 'Evaluation': "In Field", 'Title': "Around me: A system with an escort robot providing a sports player’s self-images.", 'Unnamed: 11': "Tominaga14", 'reference number': '39','image': 'images/Tominaga14.png'},
    //{'first author name': "Strohrmann13", 'Purpose': "Instructional", 'Year': "'10-'14", 'Device': "MobilePhone", 'Data': "Technique", 'Data Abstraction': "Abstract", 'Visual Encoding': "Non-visual", 'Embeddedness': "N.A.", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "Can Smartphones Help with Running Technique? - ScienceDirect", 'Unnamed: 11': "Strohrmann13", 'reference number': '40','image': 'images/Strohrmann13.png'},
    //{'first author name': "Fortmann12", 'Purpose': "Instructional", 'Year': "'10-'14", 'Device': "HeadPhone", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "Non-visual", 'Embeddedness': "N.A.", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "PaceGuard | Proceedings of the 14th international conference on Human-computer interaction with mobile devices and services companion (acm.org)", 'Unnamed: 11': "Fortmann12", 'reference number': '41','image': 'images/Fortmann12.png'},
    {'first author name': "Eriksson11", 'Purpose': "Instructional", 'Year': "'10-'14", 'Device': "ExternalDisplay", 'Data': "Performance, Technique", 'Data Abstraction': "Abstract", 'Visual Encoding': "3D, Non-visual", 'Embeddedness': "Co-located", 'Interaction Space': "Focal-Extrapersonal", 'Evaluation': "In Lab", 'Title': "Immediate effect of visual and auditory feedback to control the running mechanics of well-trained athletes (tandfonline.com)", 'Unnamed: 11': "Eriksson11", 'reference number': '42','image': 'images/Eriksson11.png'},
    {'first author name': "Higuchi11", 'Purpose': "Instructional", 'Year': "'10-'14", 'Device': "AR/VR HMD", 'Data': "Multimedia", 'Data Abstraction': "Spatial", 'Visual Encoding': "3D", 'Embeddedness': "Co-located", 'Interaction Space': "Action-Extrapersonal", 'Evaluation': "No Evaluation", 'Title': "Flying sports assistant | Proceedings of the 2nd Augmented Human International Conference (acm.org)", 'Unnamed: 11': "Higuchi11", 'reference number': '43','image': 'images/Higuchi11.png'},
    {'first author name': "Rubisch10", 'Purpose': "Instructional", 'Year': "'10-'14", 'Device': "MobilePhone", 'Data': "Performance, Physiological", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D, Textual, Non-visual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "No Evaluation", 'Title': "A mobile music concept as support for achieving target heart rate in preventive and recreational endurance training | Proceedings of the 5th Audio Mostly Conference: A Conference on Interaction with Sound (acm.org)", 'Unnamed: 11': "Rubisch10", 'reference number': '44','image': 'images/Rubisch10.png'},
    {'first author name': "Buttussi08", 'Purpose': "Instructional", 'Year': "'04-'09", 'Device': "MobilePhone", 'Data': "Performance, Physiological, Location-based", 'Data Abstraction': "Abstract", 'Visual Encoding': "Textual, Non-visual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "No Evaluation", 'Title': "MOPET: A context-aware and user-adaptive wearable system for fitness training - ScienceDirect", 'Unnamed: 11': "Buttussi08", 'reference number': '45','image': 'images/Buttussi08.png'},
    {'first author name': "Oliver06", 'Purpose': "Instructional", 'Year': "'04-'09", 'Device': "MobilePhone", 'Data': "Performance, Physiological", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D, Non-visual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Lab", 'Title': "MPTrain | Proceedings of the 8th conference on Human-computer interaction with mobile devices and services (acm.org)", 'Unnamed: 11': "Oliver06", 'reference number': '46','image': 'images/Oliver06.png'},
    {'first author name': "Gockley06", 'Purpose': "Instructional", 'Year': "'04-'09", 'Device': "SmartWatch", 'Data': "Performance, Physiological", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D, Textual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "No Evaluation", 'Title': "AVIVA | CHI '06 Extended Abstracts on Human Factors in Computing Systems (acm.org)", 'Unnamed: 11': "Gockley06", 'reference number': '47','image': 'images/Gockley06.png'},
    {'first author name': "Makikawa04", 'Purpose': "Instructional", 'Year': "'04-'09", 'Device': "MobilePhone", 'Data': "Performance, Physiological", 'Data Abstraction': "Abstract", 'Visual Encoding': "Textual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "Jogging support system with portable monitoring device and health manage software - PubMed (nih.gov)", 'Unnamed: 11': "Makikawa04", 'reference number': '48','image': 'images/Makikawa04.png'},
    {'first author name': "Balasubramaniam23", 'Purpose': "Experiential", 'Year': "'20-'24", 'Device': "Drone/Robot", 'Data': "Performance, Location-based", 'Data Abstraction': "Spatial", 'Visual Encoding': "3D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'Evaluation': "In Field", 'Title': "Running with a Drone for Pace Setting, Video Reflection, and Beyond: An Experiential Study", 'Unnamed: 11': "Balasubramaniam23", 'reference number': '3','image': 'images/Balasubramaniam23.png'},
    //{'first author name': "Van Renswouw21", 'Purpose': "Experiential", 'Year': "'20-'24", 'Device': "HeadPhone", 'Data': "Technique", 'Data Abstraction': "Spatial", 'Visual Encoding': "Non-visual", 'Embeddedness': "N.A.", 'Interaction Space': "Ambient-Extrapersonal", 'Evaluation': "In Field", 'Title': "Sensation: Sonifying the Urban Running Experience | Extended Abstracts of the 2021 CHI Conference on Human Factors in Computing Systems (acm.org)", 'Unnamed: 11': "Van Renswouw21", 'reference number': '4','image': 'images/Van Renswouw21.png'},
    {'first author name': "Noordin20", 'Purpose': "Experiential", 'Year': "'20-'24", 'Device': "MobilePhone", 'Data': "Performance, Location-based", 'Data Abstraction': "Abstract, Mixed", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "No Evaluation", 'Title': "Stay fit during COVID-19, a study using interactive jogging application (JOGA)", 'Unnamed: 11': "Noordin20", 'reference number': '5','image': 'images/Noordin20.png'},
    //{'first author name': "Gallo20", 'Purpose': "Experiential", 'Year': "'20-'24", 'Device': "MobilePhone", 'Data': "Location-based", 'Data Abstraction': "Abstract", 'Visual Encoding': "Non-visual", 'Embeddedness': "N.A.", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "RunAhead: Exploring Head Scanning based Navigation for Runners | Proceedings of the 2020 CHI Conference on Human Factors in Computing Systems (acm.org)", 'Unnamed: 11': "Gallo20", 'reference number': '6','image': 'images/Gallo20.png'},
    {'first author name': "Ioannou19", 'Purpose': "Experiential", 'Year': "'15-'19", 'Device': "AR/VR HMD", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Lab", 'Title': "Virtual Performance Augmentation in an Immersive Jump & Run Exergame | Proceedings of the 2019 CHI Conference on Human Factors in Computing Systems (acm.org)", 'Unnamed: 11': "Ioannou19", 'reference number': '7','image': 'images/Ioannou19.png'},
    {'first author name': "Ali18", 'Purpose': "Experiential", 'Year': "'15-'19", 'Device': "AR/VR HMD", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "Textual", 'Embeddedness': "Co-located", 'Interaction Space': "Focal-Extrapersonal", 'Evaluation': "In Lab", 'Title': "Virtual reality as a physical training assistant | IEEE Conference Publication | IEEE Xplore", 'Unnamed: 11': "Ali18", 'reference number': '8','image': 'images/Ali18.png'},
    {'first author name': "Yoo16", 'Purpose': "Experiential", 'Year': "'15-'19", 'Device': "AR/VR HMD", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "Textual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Lab", 'Title': "VRun: Running-in-place virtual reality exergame", 'Unnamed: 11': "Yoo16", 'reference number': '9','image': 'images/Yoo16.png'},
    {'first author name': "Mueller15", 'Purpose': "Experiential", 'Year': "'15-'19", 'Device': "Drone/Robot", 'Data': "Performance, Location-based", 'Data Abstraction': "Spatial", 'Visual Encoding': "3D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'Evaluation': "In Field", 'Title': "Jogging with a Quadcopter | Proceedings of the 33rd Annual ACM Conference on Human Factors in Computing Systems", 'Unnamed: 11': "Mueller15", 'reference number': '10','image': 'images/Mueller15.png'},
    {'first author name': "McGookin13", 'Purpose': "Experiential", 'Year': "'10-'14", 'Device': "SmartWatch", 'Data': "Location-based", 'Data Abstraction': "Mixed", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "No Evaluation", 'Title': "Investigating and supporting undirected navigation for runners | CHI '13 Extended Abstracts on Human Factors in Computing Systems (acm.org)", 'Unnamed: 11': "McGookin13", 'reference number': '11','image': 'images/McGookin13.png'},
    {'first author name': "Turunen11", 'Purpose': "Experiential", 'Year': "'10-'14", 'Device': "MobilePhone", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "Textual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Lab", 'Title': "Multimodal and mobile conversational Health and Fitness Companions | Computer Speech and Language (acm.org)", 'Unnamed: 11': "Turunen11", 'reference number': '12','image': 'images/Turunen11.png'},
    {'first author name': "Buttussi10", 'Purpose': "Experiential", 'Year': "'10-'14", 'Device': "MobilePhone", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D, Non-visual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "Smarter Phones for Healthier Lifestyles: An Adaptive Fitness Game | IEEE Journals & Magazine | IEEE Xplore", 'Unnamed: 11': "Buttussi10", 'reference number': '13','image': 'images/Buttussi10.png'},
    //{'first author name': "Sakata06", 'Purpose': "Experiential", 'Year': "'04-'09", 'Device': "HeadPhone", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "Non-visual", 'Embeddedness': "N.A.", 'Interaction Space': "Peripersonal", 'Evaluation': "No Evaluation", 'Title': "Situated Music: An Application to Interactive Jogging", 'Unnamed: 11': "Sakata06", 'reference number': '14','image': 'images/Sakata06.png'},
    //{'first author name': "Asselin05", 'Purpose': "Experiential", 'Year': "'04-'09", 'Device': "HeadPhone", 'Data': "Physiological", 'Data Abstraction': "Abstract", 'Visual Encoding': "Non-visual", 'Embeddedness': "N.A.", 'Interaction Space': "Peripersonal", 'Evaluation': "In Lab", 'Title': "Implementation and evaluation of the personal wellness coach | IEEE Conference Publication | IEEE Xplore", 'Unnamed: 11': "Asselin05", 'reference number': '15','image': 'images/Asselin05.png'},
    {'first author name': "Tong24", 'Purpose': "Social", 'Year': "'20-'24", 'Device': "MobilePhone", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Action-Extrapersonal", 'Evaluation': "In Field", 'Title': "VisTellAR: Embedding Data Visualization to Short-form Videos Using Mobile Augmented Reality.", 'Unnamed: 11': "Tong24", 'reference number': '53','image': 'images/Tong24.png'},
    {'first author name': "Baldursson21", 'Purpose': "Social", 'Year': "'20-'24", 'Device': "Drone/Robot", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D", 'Embeddedness': "Embedded", 'Interaction Space': "Peripersonal", 'Evaluation': "In Lab", 'Title': "DroRun: Drone Visual Interactions to Mediate a Running Group | Companion of the 2021 ACM/IEEE International Conference on Human-Robot Interaction", 'Unnamed: 11': "Baldursson21", 'reference number': '54','image': 'images/Baldursson21.png'},
    //{'first author name': "Wozniak15", 'Purpose': "Social", 'Year': "'15-'19", 'Device': "Other Body-worn Device", 'Data': "Multimedia", 'Data Abstraction': "Abstract", 'Visual Encoding': "Non-visual", 'Embeddedness': "N.A.", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "RUFUS | Proceedings of the 17th International Conference on Human-Computer Interaction with Mobile Devices and Services (acm.org)", 'Unnamed: 11': "No", 'reference number': '55','image': 'images/Wozniak15.png'},
    {'first author name': "Kishino14", 'Purpose': "Social", 'Year': "'10-'14", 'Device': "MobilePhone", 'Data': "Performance, Location-based", 'Data Abstraction': "Abstract, Mixed", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "Virtual Marathon System Where Humans and Agents Compete | Proceedings of the 4th International Conference on Web Intelligence, Mining and Semantics (WIMS14) (acm.org)", 'Unnamed: 11': "Kishino14", 'reference number': '56','image': 'images/Kishino14.png'},
    {'first author name': "Mauriello14", 'Purpose': "Social", 'Year': "'10-'14", 'Device': "Other Body-worn Device", 'Data': "Performance, Physiological", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D, Textual", 'Embeddedness': "Embedded", 'Interaction Space': "Ambient-Extrapersonal", 'Evaluation': "In Field", 'Title': "Social fabric fitness | Proceedings of the SIGCHI Conference on Human Factors in Computing Systems (acm.org)", 'Unnamed: 11': "Mauriello14", 'reference number': '57','image': 'images/Mauriello14.png'},
    //{'first author name': "Mueller07", 'Purpose': "Social", 'Year': "'04-'09", 'Device': "HeadPhone", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "Non-visual", 'Embeddedness': "N.A.", 'Interaction Space': "Peripersonal", 'Evaluation': "In Lab", 'Title': "Jogging over a distance: Supporting a 'jogging together' experience although being apart", 'Unnamed: 11': "Mueller07", 'reference number': '58','image': 'images/Mueller07.png'},
    {'first author name': "Consolvo06", 'Purpose': "Social", 'Year': "'04-'09", 'Device': "MobilePhone", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "Textual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "Design requirements for technologies that encourage physical activity | Proceedings of the SIGCHI Conference on Human Factors in Computing Systems (acm.org)", 'Unnamed: 11': "Consolvo06", 'reference number': '59','image': 'images/Consolvo06.png'},
    {'first author name': "Hamada22", 'Purpose': "Multipurpose", 'Year': "'20-'24", 'Device': "AR/VR HMD", 'Data': "Performance", 'Data Abstraction': "Spatial", 'Visual Encoding': "3D", 'Embeddedness': "Embedded", 'Interaction Space': "Focal-Extrapersonal", 'Evaluation': "In Field", 'Title': "Solitary Jogging with A Virtual Runner using Smartglasses | IEEE Conference Publication | IEEE Xplore", 'Unnamed: 11': "Hamada22", 'reference number': '1','image': 'images/Hamada22.png'},
    {'first author name': "Burr22", 'Purpose': "Multipurpose", 'Year': "'20-'24", 'Device': "ExternalDisplay", 'Data': "Physiological", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Focal-Extrapersonal", 'Evaluation': "In Lab", 'Title': "Breathing Training on the Run: Exploring Users Perception on a Gamified Breathing Training Application During Treadmill Running | SpringerLink", 'Unnamed: 11': "Burr22", 'reference number': '2','image': 'images/Burr22.png'},
    {'first author name': "Mulas11", 'Purpose': "Multipurpose", 'Year': "'10-'14", 'Device': "MobilePhone", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D, Textual, Non-visual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Lab", 'Title': "Everywhere run | Proceedings of the 8th International Conference on Advances in Computer Entertainment Technology (acm.org)", 'Unnamed: 11': "Mulas11", 'reference number': '50','image': 'images/Mulas11.png'},
    {'first author name': "Ahn09", 'Purpose': "Multipurpose", 'Year': "'04-'09", 'Device': "ExternalDisplay", 'Data': "Performance", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D, Textual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Lab", 'Title': "Running or gaming | Proceedings of the International Conference on Advances in Computer Entertainment Technology (acm.org)", 'Unnamed: 11': "Ahn09", 'reference number': '16','image': 'images/Ahn09.png'},
    {'first author name': "Oliveira08", 'Purpose': "Multipurpose", 'Year': "'04-'09", 'Device': "MobilePhone", 'Data': "Performance, Physiological, Location-based", 'Data Abstraction': "Abstract", 'Visual Encoding': "2D, Non-visual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "TripleBeat | Proceedings of the 10th international conference on Human computer interaction with mobile devices and services (acm.org)", 'Unnamed: 11': "Oliveira08", 'reference number': '51','image': 'images/Oliveira08.png'},
    {'first author name': "Ahtinen08", 'Purpose': "Multipurpose", 'Year': "'04-'09", 'Device': "MobilePhone", 'Data': "Performance, Physiological", 'Data Abstraction': "Abstract, Mixed", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'Evaluation': "In Field", 'Title': "Tracking Outdoor Sports --- User Experience Perspective | Proceedings of the European Conference on Ambient Intelligence (acm.org)", 'Unnamed: 11': "Ahtinen08", 'reference number': '52','image': 'images/Ahtinen08.png'},
]

var workshop=[/////////////////////////// User Proposed ///////////////////////////
    {'first author name': "1", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance", 'Visual Encoding': "2D", 'Embeddedness': "Embedded", 'Interaction Space': "Ambient-Extrapersonal", 'RawPurpose': "Instructional", 'Title': "1", 'reference number': 'UserProposed','image': 'images/1.png'},
    {'first author name': "5", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance, Physiological", 'Visual Encoding': "Textual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'RawPurpose': "Instructional", 'Title': "5", 'reference number': 'UserProposed','image': 'images/5.png'},
    {'first author name': "7", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance, Physiological", 'Visual Encoding': "Textual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'RawPurpose': "Instructional", 'Title': "7", 'reference number': 'UserProposed','image': 'images/7.png'},
    {'first author name': "9", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance, Location-based", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'RawPurpose': "Instructional", 'Title': "9", 'reference number': 'UserProposed','image': 'images/9.png'},
    {'first author name': "10", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance, Physiological", 'Visual Encoding': "Textual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'RawPurpose': "Instructional", 'Title': "10", 'reference number': 'UserProposed','image': 'images/10.png'},
    {'first author name': "11", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Location-based", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'RawPurpose': "Instructional", 'Title': "11", 'reference number': 'UserProposed','image': 'images/11.png'},
    {'first author name': "14", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance", 'Visual Encoding': "Textual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'RawPurpose': "Instructional", 'Title': "14", 'reference number': 'UserProposed','image': 'images/14.png'},
    {'first author name': "15", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Physiological", 'Visual Encoding': "2D", 'Embeddedness': "Embedded", 'Interaction Space': "Peripersonal", 'RawPurpose': "Instructional", 'Title': "15", 'reference number': 'UserProposed','image': 'images/15.png'},
    {'first author name': "16", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'RawPurpose': "Instructional", 'Title': "16", 'reference number': 'UserProposed','image': 'images/16.png'},
    {'first author name': "17", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance", 'Visual Encoding': "Textual", 'Embeddedness': "Embedded", 'Interaction Space': "Peripersonal", 'RawPurpose': "Instructional", 'Title': "17", 'reference number': 'UserProposed','image': 'images/17.png'},
    {'first author name': "19", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance, Physiological", 'Visual Encoding': "2D, Textual", 'Embeddedness': "Co-located", 'Interaction Space': "Focal-Extrapersonal", 'RawPurpose': "Instructional", 'Title': "19", 'reference number': 'UserProposed','image': 'images/19.png'},
    {'first author name': "20", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Physiological", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Focal-Extrapersonal", 'RawPurpose': "Instructional", 'Title': "20", 'reference number': 'UserProposed','image': 'images/20.png'},
    {'first author name': "22", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Physiological", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Focal-Extrapersonal", 'RawPurpose': "Instructional", 'Title': "22", 'reference number': 'UserProposed','image': 'images/22.png'},
    {'first author name': "23", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance, Physiological", 'Visual Encoding': "2D, Textual", 'Embeddedness': "Co-located", 'Interaction Space': "Focal-Extrapersonal", 'RawPurpose': "Instructional", 'Title': "23", 'reference number': 'UserProposed','image': 'images/23.png'},
    {'first author name': "24", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Physiological", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Focal-Extrapersonal", 'RawPurpose': "Instructional", 'Title': "24", 'reference number': 'UserProposed','image': 'images/24.png'},
    {'first author name': "25", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Location-based", 'Visual Encoding': "2D", 'Embeddedness': "Co-located", 'Interaction Space': "Focal-Extrapersonal", 'RawPurpose': "Instructional", 'Title': "25", 'reference number': 'UserProposed','image': 'images/25.png'},
    {'first author name': "27", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance, Physiological", 'Visual Encoding': "N.A.", 'Embeddedness': "Co-located", 'Interaction Space': "Focal-Extrapersonal", 'RawPurpose': "Instructional", 'Title': "27", 'reference number': 'UserProposed','image': 'images/27.png'},
    {'first author name': "29", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Location-based", 'Visual Encoding': "3D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Instructional", 'Title': "29", 'reference number': 'UserProposed','image': 'images/29.png'},
    {'first author name': "33", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Location-based", 'Visual Encoding': "3D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Instructional", 'Title': "33", 'reference number': 'UserProposed','image': 'images/33.png'},
    {'first author name': "34", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance, Location-based", 'Visual Encoding': "3D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Instructional", 'Title': "34", 'reference number': 'UserProposed','image': 'images/34.png'},
    {'first author name': "35", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance, Location-based", 'Visual Encoding': "3D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Instructional", 'Title': "35", 'reference number': 'UserProposed','image': 'images/35.png'},
    {'first author name': "36", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Location-based", 'Visual Encoding': "2D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Instructional", 'Title': "36", 'reference number': 'UserProposed','image': 'images/36.png'},
    {'first author name': "37", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Location-based", 'Visual Encoding': "2D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Instructional", 'Title': "37", 'reference number': 'UserProposed','image': 'images/37.png'},
    {'first author name': "38", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Location-based", 'Visual Encoding': "2D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Instructional", 'Title': "38", 'reference number': 'UserProposed','image': 'images/38.png'},
    {'first author name': "41", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance, Location-based", 'Visual Encoding': "3D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Instructional", 'Title': "41", 'reference number': 'UserProposed','image': 'images/41.png'},
    {'first author name': "45", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance, Location-based", 'Visual Encoding': "3D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Instructional", 'Title': "45", 'reference number': 'UserProposed','image': 'images/45.png'},
    {'first author name': "46", 'Purpose': "Instructional", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance, Location-based", 'Visual Encoding': "2D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Instructional", 'Title': "46", 'reference number': 'UserProposed','image': 'images/46.png'},
    {'first author name': "2", 'Purpose': "Experiential", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Multimedia", 'Visual Encoding': "N.A.", 'Embeddedness': "N.A.", 'Interaction Space': "Peripersonal", 'RawPurpose': "Experiential", 'Title': "2", 'reference number': 'UserProposed','image': 'images/2.png'},
    {'first author name': "6", 'Purpose': "Experiential", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Multimedia", 'Visual Encoding': "Textual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'RawPurpose': "Experiential", 'Title': "6", 'reference number': 'UserProposed','image': 'images/6.png'},
    {'first author name': "8", 'Purpose': "Experiential", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Multimedia", 'Visual Encoding': "Textual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'RawPurpose': "Experiential", 'Title': "8", 'reference number': 'UserProposed','image': 'images/8.png'},
    {'first author name': "13", 'Purpose': "Experiential", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Location-based", 'Visual Encoding': "3D", 'Embeddedness': "Embedded", 'Interaction Space': "Peripersonal", 'RawPurpose': "Experiential", 'Title': "13", 'reference number': 'UserProposed','image': 'images/13.png'},
    {'first author name': "18", 'Purpose': "Experiential", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Physiological", 'Visual Encoding': "3D", 'Embeddedness': "Embedded", 'Interaction Space': "Peripersonal", 'RawPurpose': "Experiential", 'Title': "18", 'reference number': 'UserProposed','image': 'images/18.png'},
    {'first author name': "26", 'Purpose': "Experiential", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Location-based", 'Visual Encoding': "3D", 'Embeddedness': "Embedded", 'Interaction Space': "Focal-Extrapersonal", 'RawPurpose': "Experiential", 'Title': "26", 'reference number': 'UserProposed','image': 'images/26.png'},
    {'first author name': "42", 'Purpose': "Experiential", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Location-based", 'Visual Encoding': "2D, Textual", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Instructional, Experiential", 'Title': "42", 'reference number': 'UserProposed','image': 'images/42.png'},
    {'first author name': "43", 'Purpose': "Experiential", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Multimedia, Location-based", 'Visual Encoding': "2D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Instructional, Experiential", 'Title': "43", 'reference number': 'UserProposed','image': 'images/43.png'},
    {'first author name': "44", 'Purpose': "Experiential", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Location-based", 'Visual Encoding': "3D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Experiential", 'Title': "44", 'reference number': 'UserProposed','image': 'images/44.png'},
    {'first author name': "3", 'Purpose': "Social", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Multimedia", 'Visual Encoding': "N.A.", 'Embeddedness': "N.A.", 'Interaction Space': "Peripersonal", 'RawPurpose': "Social", 'Title': "3", 'reference number': 'UserProposed','image': 'images/3.png'},
    {'first author name': "4", 'Purpose': "Social", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Multimedia", 'Visual Encoding': "N.A.", 'Embeddedness': "N.A.", 'Interaction Space': "Peripersonal", 'RawPurpose': "Social", 'Title': "4", 'reference number': 'UserProposed','image': 'images/4.png'},
    {'first author name': "12", 'Purpose': "Social", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance", 'Visual Encoding': "Textual", 'Embeddedness': "Co-located", 'Interaction Space': "Peripersonal", 'RawPurpose': "Social", 'Title': "12", 'reference number': 'UserProposed','image': 'images/12.png'},
    {'first author name': "21", 'Purpose': "Social", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance", 'Visual Encoding': "Textual", 'Embeddedness': "Co-located", 'Interaction Space': "Focal-Extrapersonal", 'RawPurpose': "Social", 'Title': "21", 'reference number': 'UserProposed','image': 'images/21.png'},
    {'first author name': "28", 'Purpose': "Multipurpose", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance, Location-based", 'Visual Encoding': "3D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Instructional, Experiential", 'Title': "28", 'reference number': 'UserProposed','image': 'images/28.png'},
    {'first author name': "30", 'Purpose': "Multipurpose", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance, Location-based", 'Visual Encoding': "3D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Instructional, Experiential", 'Title': "30", 'reference number': 'UserProposed','image': 'images/30.png'},
    {'first author name': "31", 'Purpose': "Multipurpose", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance, Location-based", 'Visual Encoding': "3D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Instructional, Experiential", 'Title': "31", 'reference number': 'UserProposed','image': 'images/31.png'},
    {'first author name': "32", 'Purpose': "Multipurpose", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance, Location-based", 'Visual Encoding': "3D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Instructional, Experiential", 'Title': "32", 'reference number': 'UserProposed','image': 'images/32.png'},
    {'first author name': "39", 'Purpose': "Multipurpose", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Performance, Location-based", 'Visual Encoding': "3D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Instructional, Experiential", 'Title': "39", 'reference number': 'UserProposed','image': 'images/39.png'},
    {'first author name': "40", 'Purpose': "Multipurpose", 'Year': "Workshop", 'Device': "AR/VR HMD", 'Data': "Location-based", 'Visual Encoding': "2D", 'Embeddedness': "Embedded", 'Interaction Space': "Action-Extrapersonal", 'RawPurpose': "Instructional, Experiential", 'Title': "40", 'reference number': 'UserProposed','image': 'images/40.png'},
]

var node_list = [
    {
        0: "'20-'24",
        1: "'15-'19",
        2: "'10-'14",
        3: "'04-'09",
        4: "Workshop",
        5: '',
        6: '',
        7: '',
        8: '',
        9: '',
        10: '',
        11: '',
        title: 'Year',
    },
    {
        0: 'MobilePhone',
        1: 'SmartWatch',
        2: 'HeadPhone',
        3: 'ExternalDisplay',
        4: 'AR/VR HMD',
        5: 'Other Body-worn Device',
        6: 'Drone/Robot',
        7: '',
        8: '',
        9: '',
        10: '',
        11: '',
        title: 'Device',
    },
    {
        0: 'Performance',
        1: 'Performance, Physiological',
        2: 'Performance, Physiological, Location-based',
        3: 'Performance, Technique',
        4: 'Performance, Technique, Location-based',
        5: 'Performance, Location-based',
        6: 'Physiological',
        7: 'Technique',
        8: 'Technique, Multimedia',
        9: 'Location-based',
        10: 'Multimedia',
        11: 'Multimedia, Location-based',
        title: 'Data',
    },
    // {
    //     0: 'Abstract',
    //     1: 'Spatial',
    //     2: 'Mixed',
    //     3: 'Abstract, Mixed',
    //     4: '',
    //     5: '',
    //     6: '',
    //     7: '',
    //     8: '',
    //     9: '',
    //     title: 'Data Abstraction',
    // },
    {
        0: '2D',
        1: '2D, Textual',
        2: '2D, Non-visual',
        3: '2D, Textual, Non-visual',
        4: '3D',
        5: '3D, Non-visual',
        6: 'Textual',
        7: 'Textual, Non-visual',
        8: 'N.A.',
        9: '',
        10: '',
        11: '',
        title: 'Visual Encoding',
    },
    {
        0: 'Co-located',
        1: 'Embedded',
        2: 'N.A.',
        3: '',
        4: '',
        5: '',
        6: '',
        7: '',
        8: '',
        9: '',
        10: '',
        11: '',
        title: 'Embeddedness',
    },
    {
        0: 'Peripersonal',
        1: 'Focal-Extrapersonal',
        2: 'Action-Extrapersonal',
        3: 'Ambient-Extrapersonal',
        4: '',
        5: '',
        6: '',
        7: '',
        8: '',
        9: '',
        10: '',
        11: '',
        title: 'Interaction Space',
    },
    // {
    //     0: 'In Field',
    //     1: 'In Lab',
    //     2: 'No Evaluation',
    //     3: '',
    //     4: '',
    //     5: '',
    //     6: '',
    //     7: '',
    //     8: '',
    //     9: '',
    //     title: 'Evaluation',
    // },
    /*  {
        0: '1-5',
        1: '6-10',
        2: '11-15',
        3: '16-20',
        4: 'Greater than 20',
        5: 'Not Applicable',
        6: '',
        7: '',
        title: '# of Participants',
      },*/
    {
        0: 'Instructional',
        1: 'Experiential',
        2: 'Social',
        3: 'Multipurpose',
        4: '',
        5: '',
        6: '',
        7: '',
        8: '',
        9: '',
        10: '',
        11: '',
        title: 'Purpose',
    },
];
